#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
PREFIX=''

if [[ "${BRANCH_NAME}" == */* ]]; then
    PREFIX=$(echo ${BRANCH_NAME} | cut -d '/' -f2)
fi

FIRST_LINE=$(head -n1 ${COMMIT_MSG_FILE})

if [ -z "$FIRST_LINE" ]; then
    # Check if the branch name contains an issue number
    ISSUE_NUMBER=$(echo ${BRANCH_NAME} | sed -n 's/.*\/\([0-9]*\)/\1/p')

    if [ -z "$ISSUE_NUMBER" ]; then
        echo "Error: The branch name must contain an issue number."
        exit 1
    fi

    if [[ ! "$FIRST_LINE" =~ ^$PREFIX: #${ISSUE_NUMBER} ]]; then
        if [[ "$PREFIX" =~ ^(fix|chore|refactor|test|feat|doc)$ ]]; then
            sed -i ".bak" "1s/^/$PREFIX: #${ISSUE_NUMBER} /" ${COMMIT_MSG_FILE}
        else
            echo "Error: The commit message must start with one of the prefixes: fix, chore, refactor, test, feat, doc."
            exit 1
        fi
    fi
fi
